### PR TITLE
fix(services): added services page component

### LINKED ISSUE #38: Create common component for Services page
**!** Text align need to be dynamically setup

Screenshot 2021-01-29 at 16 53 00

### PR DESCRIPTION
**Pull request by TanyaDolgopolova**
**For working this branch need PR #46 to be merged**

Close #38

### CODE REVIEW

**Review by cobraz — CHANGES_REQUESTED** [review]
This probably needs to be rebased after #46 is merged. I don't see an example of the implementation in the [deployment preview](https://deploy-preview-47--bjerk-website-dev.netlify.app/). We probably want @AnneMatilde to review components, so I'll leave it to her to approve design-related things.

Can you rebase and ask me for a new review?

File: web/src/components/services-page/service-list-item.tsx [hunk 1]
```diff
@@ -0,0 +1,65 @@
+import Img, { FluidObject } from 'gatsby-image';
+import React from 'react';
+import { Box, Button, Container, Flex, Grid, Heading, Label } from 'theme-ui';
+import { Link } from '../custom-link';
+
+export interface ServiceListItemProps {
```
Comment (cobraz) [inline web/src/components/services-page/service-list-item.tsx:6]:
```suggestion
// TODO: Replace with automatically generated types when available from Sanity.
export interface ServiceListItemProps {
```

File: web/src/components/services-page/service-list-item.tsx [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+  personPhoto?: FluidObject;
+  textAlign: 'left' | 'right';
+  dividedPhoto?: FluidObject;
+}
+
+// TODO: fix image showing when Sanity will be done
+export const ServiceListItem: React.FC<{ data: ServiceListItemProps }> = ({
+  data,
+}) => (
+  <Container id={data.name} sx={{ mt: '10%' }}>
```
Comment (cobraz) [inline web/src/components/services-page/service-list-item.tsx:24]:
```suggestion
  <Container id={data.name} sx={{ mt: 4 }}>
```

or

```suggestion
  <Container id={data.name} sx={{ mt: '4rem' }}>
```

What ever makes the most sense. Using percentage is discouraged since we have a size matrix.

**Review by cobraz — APPROVED** [review]
Looks good. 👍 Make sure to get @AnneMatilde design approval.
